default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: db/development.sqlite3
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
