default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: db_development
test:
  <<: *default
  database: db_test

production:
  <<: *default
  database: db_production
